<!DOCTYPE html>
<html>
<body>
  
<h1>JavaScript Errors</h1>

<h2>Throw, and Try...Catch...Finally</h2>

<p>The try statement defines a code block to run (to try).<br><br>

The catch statement defines a code block to handle any error.<br><br>

The finally statement defines a code block to run regardless of the result.<br><br>

The throw statement defines a custom error.
</p>

<h2>Errors Will Happen!</h2>
<p>
When executing JavaScript code, different errors can occur.<br><br>

Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.
</p>
<h3>Example</h3>
<p>In this example we misspelled "alert" as "adddlert" to deliberately produce an error:</p>

<h3>Output:</h3>
<code>
<h2>JavaScript Error Handling</h2>
<p>How to use <b>catch</b> to display an error.</p>

< p id="demo"></p>
< script> <br>
try {<br>
  adddlert("Welcome guest!");<br>
}<br>
catch(eror) {<br>
document.getElementById("demo").innerHTML = eror.message;<br>
}<br>
< /script>
</code>

<br><br>
////////////////////////////////////////

<h3>Output:</h3>
<div>
<h2>JavaScript Error Handling</h2>
<p>How to use <b>catch</b> to display an error.</p>

<p id="demox"></p>
<script>
try {
  adddlert("Welcome guest!");
}
catch(eror1) {
document.getElementById("demox").innerHTML = eror1.message;
}
</script>
</div>

<br>
/////////////////////////////////////////

<p><b>Note:</b>JavaScript catches adddlert as an error, and executes the catch code to handle it.</p>

<h2>JavaScript try and catch</h2>
<p>The try statement allows you to define a block of code to be tested for errors while it is being executed.<br><br>

The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.<br><br>

The JavaScript statements try and catch come in pairs:
</p>

<code>
try {<br>
  Block of code to try<br>
}<br>
catch(err) {<br>
  Block of code to handle errors<br>
}
</code>

<h2>JavaScript Throws Errors</h2>

<p>When an error occurs, JavaScript will normally stop and generate an error message.<br><br>

The technical term for this is: JavaScript will throw an exception (throw an error).
</p>

<p>
JavaScript will actually create an Error object with two properties: name and message.
</p>
<h2>The throw Statement</h2>
<p>
The throw statement allows you to create a custom error.<br><br>

Technically you can throw an exception (throw an error).<br>

The exception can be a JavaScript String, a Number, a Boolean or an Object:
</p>
<code>
throw "Too big";   <br>
// throw a text <br>
throw 500;  <br>
// throw a number
</code>

<p>If you use throw together with try and catch, you can control program flow and generate custom error messages.</p>

<h2>Input Validation Example</h2>
<p>
This example examines input. If the value is wrong, an exception (err) is thrown.

The exception (err) is caught by the catch statement and a custom error message is displayed:
</p>


<code>
<p>Please input a number between 5 and 10:</p><br>
< input id="demo" type="text"><br>
< button type="button" onclick="myFunction()">Test Input< /button><br>
< p id="p01"></p><br>
< script><br>
function myFunction() { <br>
  const message = document.getElementById("p01");<br>
  message.innerHTML = "";<br>
  let x = document.getElementById("demo").value;<br>
  try {<br>
    if(x == "") throw "empty";<br>
    if(isNaN(x)) throw "not a number";<br>
    x = Number(x);<br>
    if(x < 5) throw "too low";<br>
    if(x > 10) throw "too high";<br>
  }<br>
  catch(err) {<br>
    message.innerHTML = "Input is " + err;
  }<br>
}<br>
< /script>
</body>
</code>

<h3>Output:</h3>
<div>

<h2>JavaScript try catch</h2>

<p>Please input a number between 5 and 10:</p>
<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="p01"></p>

<script>
function myFunction() {
  const message = document.getElementById("p01");
  message.innerHTML = "";
  let x = document.getElementById("demo").value;
  try { 
    if(x == "")  throw "empty";
if(isNaN(x)) throw "not a number";
    x = Number(x);
    if(x < 5)  throw "too low";
    if(x > 10)   throw "too high";
  }
  catch(err) {
    message.innerHTML = "Input is " + err;
}
}
</script>

</div>

<h2>HTML Validation</h2>
<p>The code above is just an example.<br>

Modern browsers will often use a combination of JavaScript and built-in HTML validation, using predefined validation rules defined in HTML attributes:</p>

<code>
< input id="demo" type="number" min="5" max="10" step="1">
</code>

<p>You can read more about forms validation in a later chapter of this tutorial.</p>

<h2>The finally Statement</h2>

<p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>

<h3>Syntax</h3>

<div>
try { <br>
  Block of code to try <br>
} <br>
catch(err) { <br>
  Block of code to handle errors <br>
} <br>
finally { <br>
  Block of code to be executed regardless of the try / catch result <br>
}
</div>

<h3>example</h3>

<code>
function myFunction() {<br>
  const message = document.getElementById("p01");<br>
  message.innerHTML = "";<br>
  let x = document.getElementById("demo").value;<br>
  try {<br>
    if(x == "") throw "is empty";<br>
    if(isNaN(x)) throw "is not a number";<br>
    x = Number(x);<br>
    if(x > 10) throw "is too high";<br>
    if(x < 5) throw "is too low";<br>
  }<br>
  catch(err) {<br>
    message.innerHTML = "Error: " + err + ".";<br>
  }<br>
  finally {<br>
    document.getElementById("demo").value = "";<br>
  }
</code>


<h3>Output:</h3>  
/////////////////////////////////////////
<div>
<h2>JavaScript try catch</h2>
<p>Please input a number between 5 and 10:</p>
<input id="demo22" type="text">
<button type="button" onclick="myFunction22()">Test Input</button>

<p id="p02"></p>
<script>
function myFunction22() {
  const message22 = document.getElementById("p02");
  message22.innerHTML = "";
  let x22 = 
document.getElementById("demo22").value;
  try { 
    if(x22 == "")  throw "is empty";
    if(isNaN(x22)) throw "is not a number";
    x22 = Number(x22);
    if(x22 > 10)   throw "is too high";
if(x22 < 5)  throw "is too low";
  }
  catch(err) {
    message22.innerHTML = "Input " + err;
  }
  finally {
document.getElementById("demo22").value = "";
  }
}
</script>
</div>
//////////////////////////////////////

<h2>The Error Object</h2>
<p>JavaScript has a built in error object that provides error information when an error occurs.<br><br>

The error object provides two useful properties: name and message.<br><br>
</p>

<h2>Error Object Properties</h2>
<table>
  <tr>
    <th>Property</th>
    <th>Description </th>
  </tr>
  <tr>
    <td>name </td>
    <td>Sets or returns an error name</td>
  </tr>
  <tr>
    <td>message	</td>
    <td>Sets or returns an error message (a string)</td>
  </tr>
</table>

<h2>Error Name Values</h2>
<p>Six different values can be returned by the error name property:</p>

<table>
  <tr>
    <th>Error Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>EvalError	</td>
    <td>An error has occurred in the eval() function</td>
  </tr>
<tr>
    <td>RangeError</td>
    <td>A number "out of range" has occurred</td>
  </tr>
<tr>
    <td>ReferenceError	</td>
    <td>An illegal reference has occurred</td>
  </tr>
<tr>
    <td>SyntaxError</td>
    <td>A syntax error has occurred</td>
  </tr>
<tr>
    <td>TypeError</td>
    <td>A type error has occurred</td>
  </tr>
<tr>
    <td>URIError</td>
    <td>An error in encodeURI() has occurred</td>
  </tr>

</table>
<p>The six different values are described below.</p>

<h2>Eval Error</h2>
<p>
An EvalError indicates an error in the eval() function.<br>

Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead.
</p>

<h2>Range Error</h2>
<p>

A RangeError is thrown if you use a number that is outside the range of legal values.<br>

For example: You cannot set the number of significant digits of a number to 500.
</p>

<h3>Example</h3>

<code>
let num = 1;<br>
try {<br>
  num.toPrecision(500);   <br>
  // A number cannot have 500 significant digits<br>
}<br>
catch(err) {<br>
  document.getElementById("demo").innerHTML = err.name;<br>
}<br>
</code>

<h3>Output:</h3>
<div>
<p>You cannot set the number of significant digits of a number to 500:</p>
<p id="demoRange">
<script>
let numRange = 1;
try {
numRange.toPrecision(500);
}
catch(err) {
  document.getElementById("demoRange").innerHTML = err.name;
}
</script>
</div>

<h2>Reference Error</h2>
<p>A ReferenceError is thrown if you use (reference) a variable that has not been declared:</p>

<h3>Example</h3>
<code>
let x = 5;<br>
try { <br>
  x = y + 1;  <br>
  // y cannot be used (referenced)
}<br>
catch(err) { <br>
  document.getElementById("demo").innerHTML = err.name;<br>
}
</code>

<h3>Output:</h3>
<div>
<p>You cannot use the value of a non-existing variable:</p>
<p id="demo1"></p>
<script>
let x = 5;
try {
  x = y + 1;
}
catch(err) {
  document.getElementById("demo1").innerHTML = err.name;
}
</script>
</div>

<h2>Syntax Error</h2>
<p>A SyntaxError is thrown if you try to evaluate code with a syntax error.</p>

<h3>Example</h3>
<code>
try {<br>
  eval("alert('Hello)");  <br>
  // Missing ' will produce an error<br>
}<br>
catch(err) {<br>
  document.getElementById("demo").innerHTML = err.name;<br>
}
</code>

<h3>Output:</h3>

<div>
<p>You cannot evaluate code that contains a syntax error:</p>
<p id="demo2"></p>
<script>
try {
  eval("alert('Hello)");
}
catch(err) {
document.getElementById("demo2").innerHTML = err.name;
}
</script>
</div>

<h2>Type Error</h2>
<p>A TypeError is thrown if you use a value that is outside the range of expected types:</p>

<h3>Example</h3>
<code>
let num = 1;<br>
try {<br>
  num.toUpperCase();  <br>
  // You cannot convert a number to upper case <br>
}<br>
catch(err) {<br>
  document.getElementById("demo").innerHTML = err.name;<br>
}
</code>

<h3>Output:</h3>

<div>
<p>You cannot convert a number to upper case:</p>
<p id="demo3"></p>
<script>
let num = 1;
try {
  num.toUpperCase();
}
catch(err) {
  document.getElementById("demo3").innerHTML = err.name;
}
</script>
</div>

<h2>URI (Uniform Resource Identifier) Error
</h2>

<p>A URIError is thrown if you use illegal characters in a URI function:</p>

<h3>Example</h3>
<code>
try { <br>
  decodeURI("%%%");  <br>
  // You cannot URI decode percent signs
} <br>
catch(err) {<br>
  document.getElementById("demo").innerHTML = err.name;<br>
}
</code>

<h3>Output:</h3>

<div>
<p>Some characters cannot be decoded with decodeURI():</p>
<p id="demo4"></p>
<script>
try {
  decodeURI("%%%");
}
catch(err) {
  document.getElementById("demo4").innerHTML = err.name;
}
</script>
</div>

<h2>Non-Standard Error Object Propertie
</h2>

<p>Mozilla and Microsoft define some non-standard error object properties:

<ul>
  <li>fileName (Mozilla) </li>
  <li>lineNumber (Mozilla) </li>
  <li>columnNumber (Mozilla) </li>
  <li>stack (Mozilla)</li>
  <li>description (Microsoft) </li>
  <li>number (Microsoft)</li>
</ul>

Do not use these properties in public web sites. They will not work in all browsers.</p>

<h3>Complete Error Reference</h3>
<p>For a complete reference of the Error object, go to our Complete JavaScript Error Reference.
</p>


</body>
</html>